server:
  port: 8888
  servlet:
    context-path: /

apollo:
  bootstrap:
    enabled: true
    autoUpdateInjectedSpringProperties: true
  meta: http://localhost:8080
  env: dev

app:
  id: SampleApp

namespace: application